### ISSUE TITLE
'Run external program on torrent completion' does not work in flatpak version

### ISSUE THREAD

**Issue by luzpaz** [flathub/org.qbittorrent.qBittorrent#133]
https://github.com/qbittorrent/qBittorrent/issues/16989

**Comment by Erick555** [comment]
As commented in the linked thread this is by design. It can be worked around by adding `--talk-name=org.freedesktop.Flatpak` permission then executing external commands like `flatpak-spawn --host <actual_command>`.

I wouldn't recommend doing this in app by default since it makes escaping sandbox trivial (it also requires acceptance from flathub admins).

**Comment by luzpaz** [comment]
Thanks.  
Closing.
